#!/usr/bin/env bash

#
# Set up reverse tunnel for remote access: RDP, SSH, [L]VNC, etc.
#
# IMPORTANT:
#
# * Make sure the remote SSH server has `GatewayPorts clientspecified`
#   in its `/etc/ssh/sshd_config`.

#--------------------------------------- Hooks

P="AutoSSH"

set_ssh_mode() {
  O+=(
    -R 0.0.0.0:${C_R_PORT}:${C_L_HOST}:${C_L_PORT}
  )
}

#--------------------------------------- Main

# Use the framework.
. "${0%/*}/lib/core1.script.sh"
