#!/usr/bin/env bash

#
# Monitor 2 RDP tunnels at once.
#

#--------------------------------------- Functions

# Run the same subcommand for all tunnels.
# $1: Subcommand.
all() {
  p1_ctl "$@"
  p2_ctl "$@"
  p3_ctl "$@"
}

print_combo_status() {
  # NOTE: Status command output MUST be muted, otherwise it'll damage the productive output.
  p1_ctl status > /dev/null; local R1=$?
  p2_ctl status > /dev/null; local R2=$?
  p3_ctl status > /dev/null; local R3=$?
  echo "${R1},${R2},${R3}"
}

p1_ctl() {
  ./rdp1-ctl "$@" 2>&1 | ppipe "rdp1-ctl: "
}

p2_ctl() {
  ./rdp2-ctl "$@" 2>&1 | ppipe "rdp2-ctl: "
}

p3_ctl() {
  ./rdp3-ctl "$@" 2>&1 | ppipe "rdp3-ctl: "
}

#--------------------------------------- Hooks

do_start() {
  all start
}

do_stop() {
  all stop
}

print_status() {
  all status
}

is_running() {
  test "`print_combo_status`" = "0,0,0"
}

is_stopped() {
  test "`print_combo_status`" = "1,1,1"
}

#--------------------------------------- Main

# Use the framework.
. "${0%/*}/mon1.script.sh"
