#!/usr/bin/env bash

#
# Set up SOCKS tunnel.
#

#--------------------------------------- Hooks

P="AutoSSH"

set_ssh_mode() {
  O+=(
    -D ${C_SOCKS_HOST:-0.0.0.0}:${C_SOCKS_PORT}
  )
}

#--------------------------------------- Main

# Use the framework.
. "${0%/*}/lib/core1.script.sh"
