#!/usr/bin/env bash

#
# Monitor the named script.
#

#--------------------------------------- Hooks

P="Monitor"

LOG_BN="monitor.log"
PID_BN="monitor.pid"

#--------------------------------------- Main

# Use the framework.
. "${0%/*}/lib/mon1.script.sh"
