#!/usr/bin/env bash

#
# Control the named script.
#

#--------------------------------------- Hooks

P="AutoSSH"

#--------------------------------------- Main

# Use the framework.
. "${0%/*}/lib/ctl1.script.sh"
