#!/usr/bin/env bash

#
# Control the named script.
#

#--------------------------------------- Hooks

P="Monitor"

FORCED_BG="!"
LOG_BN="monitor.log"
PID_BN="monitor.pid"

#--------------------------------------- Main

# Use the framework.
. "${0%/*}/lib/ctl2.script.sh"
